name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        with:
          github_user_name: AllanDutra
          outputs: 
              dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#FFFFFF&color_dots=#161B22,#6D28D9,#7C3AED,#8B5CF6,#A78BFA

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
