name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v2
        with:
          github_user_name: AllanDutra
          color_snake: '#FFFFFF'
          color_dots:  '#7937C4,#7134B8,#612C9E,#4A2278,#231038'
          outputs: blob/output/github-contribution-grid-snake.svg?color_snake=#FFFFFF&color_dots=#7937C4,#7134B8,#612C9E,#4A2278,#231038

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
